## Logistic Regression Implementation

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns      
%matplotlib inline


In [3]:
## import datasets from sklearn
from sklearn.datasets import make_classification
# make_classification is a utility function to generate a synthetic classification dataset.
# It's commonly used for testing and demonstrating machine learning models.

In [4]:
#create dataset
X,y=make_classification(n_samples=1000,n_features=10,n_classes=2,random_state=30)

In [5]:
X

array([[-2.26689933,  1.49959359,  0.75965452, ..., -0.74250649,
         1.0170277 , -1.45644926],
       [-1.28997309,  0.8331157 ,  0.41769573, ...,  0.2121813 ,
        -0.36359052, -0.83983932],
       [ 0.22216965,  1.38907741,  1.03319923, ...,  0.15190194,
         0.72825596,  0.98205686],
       ...,
       [ 0.20849575,  1.14820907,  0.85756747, ...,  1.11610857,
         0.00848992,  0.83671534],
       [-2.38812834, -0.34532195, -0.58792652, ..., -0.78802051,
        -0.22142448, -2.58624305],
       [ 0.04440334,  0.73896088,  0.53916948, ..., -0.75412292,
         0.30822932,  0.44835661]])

In [6]:
#conerting x into dataframe
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0   -2.266899  1.499594  0.759655  0.122765 -2.315735 -0.019930 -0.132149   
1   -1.289973  0.833116  0.417696 -0.284231 -1.066789 -0.073931 -0.026814   
2    0.222170  1.389077  1.033199  0.598068  0.384157 -0.217773  1.403139   
3   -1.266009  1.337652  0.784920  0.733756 -1.161272 -0.172708  0.211214   
4   -1.027363  0.667609  0.335617  0.250314  1.582328  0.121074  0.034026   
..        ...       ...       ...       ...       ...       ...       ...   
995  0.027508  0.568849  0.414103  0.662608 -0.284284 -0.110962 -0.361262   
996  2.143101  0.214668  0.458938 -1.087562  0.382458 -0.970834  0.288722   
997  0.208496  1.148209  0.857567 -0.314116 -1.741188  0.967866 -0.632848   
998 -2.388128 -0.345322 -0.587927 -0.181420  0.206793  0.540870  0.431581   
999  0.044403  0.738961  0.539169 -0.632168 -0.212384 -1.446757 -1.275500   

            7         8         9  
0   -0.742506  1.017028 -1.456449  
1    0.212181 -0.363591 -0.839839  
2    0.151902  0.728256  0.982057  
3   -0.424339  1.685622 -0.540096  
4    0.948339  0.895196 -0.666628  
..        ...       ...       ...  
995  0.493847 -0.551548  0.338443  
996 -0.843561  0.507008  2.268858  
997  1.116109  0.008490  0.836715  
998 -0.788021 -0.221424 -2.586243  
999 -0.754123  0.308229  0.448357  

[1000 rows x 10 columns]

In [7]:
y

array([1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1,

### Train-Test Split

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

### Implement Logistic Regression

In [9]:
## Model Selection
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression()

In [10]:
logistic.fit(X_train,y_train)

LogisticRegression()

In [11]:
y_pred=logistic.predict(X_test)
print(y_pred)

[1 0 1 0 1 1 1 0 0 0 0 1 0 0 1 1 1 1 0 1 1 1 0 1 0 0 0 0 1 0 1 0 1 0 1 1 0
 0 0 0 0 1 1 1 0 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 0 0 1 0 1 1 0 1 0 1 1 1 1 0
 0 0 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 1 1 0 1 0 0
 0 1 0 0 1 0 0 0 0 1 1 1 0 0 1 1 1 0 1 1 1 1 1 0 1 1 0 1 1 1 1 1 0 0 1 1 1
 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 1 1 0 1 0 1 1 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1
 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 0 0 0 0 0 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 1
 1 0 1 1 1 0 0 1 0 1 0 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 1
 1 0 0 0 1 0 1 1 1 1 1 1 1 1 1 1 0 1 0 1 0 1 1 1 1 0 1 0 1 1 0 0 1 1 1 1 0
 0 0 0 0]


In [12]:
# logistic.predict_proba(X_test)

### Performance metrices

In [13]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report 


In [14]:
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.9666666666666667
[[134   5]
 [  5 156]]
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       139
           1       0.97      0.97      0.97       161

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300



# Hperparameter and Cross Validation

# Gridsearch CV

In [15]:
model=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg','lbgfs','liblinear','sag','saga']

In [16]:
#key-value pair
params=dict(penalty=penalty,C=c_values,solver=solver)

In [17]:
#stratisfied kfold
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [18]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [19]:
print(grid)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbgfs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')


In [20]:
grid.fit(X_train,y_train)

c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
225 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver =

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbgfs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [21]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'liblinear'}

In [22]:
grid.best_score_

0.9285714285714286

In [23]:
y_pred=grid.predict(X_test)

In [24]:
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.9666666666666667
[[134   5]
 [  5 156]]
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       139
           1       0.97      0.97      0.97       161

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300



# Randomized searchCV

In [25]:
model=LogisticRegression()

In [26]:
from sklearn.model_selection import RandomizedSearchCV
randomCV=RandomizedSearchCV(estimator=model,param_distributions=params,scoring='accuracy',cv=5)

In [27]:
print(randomCV.fit(X_train,y_train))

RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbgfs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')


c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
35 f

In [28]:
randomCV.best_score_

0.9242857142857142

In [29]:
randomCV.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 1.0}

In [30]:
y_pred=randomCV.predict(X_test)

In [31]:
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.9666666666666667
[[134   5]
 [  5 156]]
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       139
           1       0.97      0.97      0.97       161

    accuracy                           0.97       300
   macro avg       0.97      0.97      0.97       300
weighted avg       0.97      0.97      0.97       300



In [32]:
model.predict(X_test)

NotFittedError: This LogisticRegression instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.