## Logistic Regression Implementation

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt 
import seaborn as sns      
%matplotlib inline


In [2]:
## import datasets from sklearn
from sklearn.datasets import make_classification
# make_classification is a utility function to generate a synthetic classification dataset.
# It's commonly used for testing and demonstrating machine learning models.

In [3]:
#create dataset
X,y=make_classification(n_samples=1000,n_features=10,n_informative=3,n_classes=3,random_state=30)

In [4]:
X

array([[-3.79819435, -0.0116566 ,  2.69788584, ...,  2.30836816,
        -1.22524321,  0.89107142],
       [ 0.32796152,  1.24487292,  1.42632383, ..., -1.0376978 ,
        -0.38289968, -0.95982748],
       [-1.74824353, -1.08736225,  0.92779641, ...,  0.0831013 ,
         0.35367575, -1.29512529],
       ...,
       [-0.27947037, -1.13770969, -1.03312521, ...,  0.50507126,
        -0.28197648, -0.17646782],
       [-0.27340623, -1.14130812, -0.57072947, ..., -0.20958318,
         0.31013614, -1.9053905 ],
       [-1.51369089, -1.02942421,  0.07794309, ...,  1.05119938,
        -1.37445507,  1.89162191]])

In [5]:
#conerting x into dataframe
pd.DataFrame(X)

0         1         2         3         4         5         6  \
0   -3.798194 -0.011657  2.697886 -1.655996  0.289784  3.009481  0.030442   
1    0.327962  1.244873  1.426324 -0.589466  0.778635 -1.773465 -0.811293   
2   -1.748244 -1.087362  0.927796 -0.794701  0.209749  1.220564 -0.131415   
3    1.633759 -0.514056 -1.035554  3.167158  1.926773 -1.734906 -0.018181   
4   -1.676550 -0.572806  1.658670  0.141888  0.082959  0.412376 -0.333752   
..        ...       ...       ...       ...       ...       ...       ...   
995 -0.515008 -1.741889 -1.063894  0.003813  0.196681  1.356060  1.444784   
996  2.288188  1.119427 -2.675092  0.628696  0.998092  0.156560  1.041070   
997 -0.279470 -1.137710 -1.033125  0.197084  0.824720  1.231157  1.203355   
998 -0.273406 -1.141308 -0.570729  3.148740 -0.222392  0.612289 -0.035397   
999 -1.513691 -1.029424  0.077943 -1.070160 -0.442880  1.961366 -0.321671   

            7         8         9  
0    2.308368 -1.225243  0.891071  
1   -1.037698 -0.382900 -0.959827  
2    0.083101  0.353676 -1.295125  
3   -1.879674  0.608913  1.276283  
4   -0.451915 -0.461265 -0.546702  
..        ...       ...       ...  
995  0.136709  1.466615  2.386387  
996  1.692960 -1.408650 -1.312467  
997  0.505071 -0.281976 -0.176468  
998 -0.209583  0.310136 -1.905390  
999  1.051199 -1.374455  1.891622  

[1000 rows x 10 columns]

In [6]:
y

array([1, 0, 2, 0, 2, 2, 1, 2, 2, 0, 2, 1, 1, 2, 2, 2, 1, 2, 1, 2, 2, 2,
       1, 0, 0, 2, 2, 0, 1, 1, 0, 0, 2, 0, 1, 0, 2, 1, 2, 0, 0, 1, 2, 0,
       1, 0, 0, 0, 1, 2, 2, 2, 0, 0, 1, 0, 2, 0, 1, 0, 0, 1, 2, 2, 2, 2,
       0, 2, 0, 2, 1, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1, 1, 0, 1, 2, 2, 2, 0,
       0, 1, 0, 2, 2, 2, 0, 1, 2, 2, 2, 0, 1, 2, 0, 0, 1, 1, 1, 2, 2, 0,
       1, 0, 2, 2, 0, 2, 2, 0, 2, 1, 2, 1, 2, 2, 2, 1, 0, 1, 1, 2, 0, 0,
       2, 2, 1, 0, 2, 0, 2, 2, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 2, 1, 2,
       2, 1, 1, 0, 1, 0, 2, 0, 2, 1, 2, 0, 0, 2, 2, 2, 1, 1, 1, 2, 0, 0,
       2, 0, 0, 1, 0, 2, 1, 2, 0, 2, 1, 0, 1, 2, 2, 1, 2, 2, 2, 1, 2, 1,
       2, 1, 2, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2, 0, 0, 1, 2, 2, 2, 1, 0, 1,
       1, 0, 0, 1, 1, 2, 2, 0, 1, 0, 0, 1, 1, 2, 1, 2, 0, 2, 2, 0, 0, 0,
       0, 0, 2, 0, 2, 0, 2, 2, 0, 0, 0, 2, 0, 1, 0, 0, 1, 0, 0, 2, 0, 0,
       1, 1, 2, 1, 0, 1, 2, 0, 1, 1, 1, 2, 1, 1, 0, 2, 1, 1, 2, 1, 2, 1,
       1, 0, 2, 0, 1, 1, 1, 0, 1, 0, 0, 0, 2, 1, 2,

### Train-Test Split

In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.30,random_state=42)

### Implement Logistic Regression

In [9]:
## Model Selection
from sklearn.linear_model import LogisticRegression
logistic=LogisticRegression(multi_class='ovr')

In [10]:
logistic.fit(X_train,y_train)

c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(multi_class='ovr')

In [11]:
y_pred=logistic.predict(X_test)
print(y_pred)

[0 0 2 0 0 1 0 1 2 2 1 0 0 0 2 1 1 2 2 0 1 0 1 0 2 2 0 1 0 2 2 1 2 2 1 0 2
 2 1 1 2 0 1 1 1 0 0 1 2 2 1 1 2 1 1 0 1 2 0 2 0 1 0 1 0 0 0 0 1 1 1 1 0 2
 1 2 2 0 1 0 0 0 2 2 0 1 1 0 0 2 2 0 0 0 0 0 0 2 2 2 1 0 2 0 1 2 2 1 2 2 0
 0 2 2 1 1 0 1 0 0 2 2 0 0 2 0 2 2 2 2 2 0 1 1 0 0 2 1 2 2 0 1 2 2 2 1 1 2
 2 0 2 1 2 2 0 1 0 2 1 1 2 1 1 1 0 1 0 1 1 1 1 2 2 1 0 1 0 0 2 0 2 1 0 2 0
 2 1 0 2 2 0 2 1 1 0 2 1 1 0 1 1 0 1 2 2 0 0 1 1 0 2 1 1 0 0 0 0 2 0 0 0 0
 1 0 1 2 0 2 0 0 1 1 1 0 2 0 1 1 2 2 0 1 1 1 2 2 1 2 2 1 1 0 2 2 1 0 0 1 0
 2 1 0 2 2 2 1 2 0 2 1 1 2 1 0 0 2 2 1 1 2 2 1 0 1 0 0 2 1 1 0 2 2 2 0 0 2
 2 2 0 1]


In [37]:
# logistic.predict_proba(X_test)

### Performance metrices

In [12]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report 


In [13]:
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.7
[[69 21 18]
 [20 65  7]
 [13 11 76]]
              precision    recall  f1-score   support

           0       0.68      0.64      0.66       108
           1       0.67      0.71      0.69        92
           2       0.75      0.76      0.76       100

    accuracy                           0.70       300
   macro avg       0.70      0.70      0.70       300
weighted avg       0.70      0.70      0.70       300



# Hperparameter and Cross Validation

# Gridsearch CV

In [14]:
model=LogisticRegression()
penalty=['l1','l2','elasticnet']
c_values=[100,10,1.0,0.1,0.01]
solver=['newton-cg','lbgfs','liblinear','sag','saga']

In [15]:
#key-value pair
params=dict(penalty=penalty,C=c_values,solver=solver)

In [16]:
#stratisfied kfold
from sklearn.model_selection import StratifiedKFold
cv=StratifiedKFold()

In [17]:
from sklearn.model_selection import GridSearchCV
grid=GridSearchCV(estimator=model,param_grid=params,scoring='accuracy',cv=cv,n_jobs=-1)

In [18]:
print(grid)

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbgfs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')


In [19]:
grid.fit(X_train,y_train)

c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
225 fits failed out of a total of 375.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver =

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=None, shuffle=False),
             estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [100, 10, 1.0, 0.1, 0.01],
                         'penalty': ['l1', 'l2', 'elasticnet'],
                         'solver': ['newton-cg', 'lbgfs', 'liblinear', 'sag',
                                    'saga']},
             scoring='accuracy')

In [20]:
grid.best_params_

{'C': 0.1, 'penalty': 'l1', 'solver': 'saga'}

In [21]:
grid.best_score_

0.7328571428571429

In [22]:
y_pred=grid.predict(X_test)

In [23]:
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.7433333333333333
[[84 11 13]
 [21 65  6]
 [16 10 74]]
              precision    recall  f1-score   support

           0       0.69      0.78      0.73       108
           1       0.76      0.71      0.73        92
           2       0.80      0.74      0.77       100

    accuracy                           0.74       300
   macro avg       0.75      0.74      0.74       300
weighted avg       0.75      0.74      0.74       300



# Randomized searchCV

In [24]:
model=LogisticRegression()

In [25]:
from sklearn.model_selection import RandomizedSearchCV
randomCV=RandomizedSearchCV(estimator=model,param_distributions=params,scoring='accuracy',cv=5)

In [26]:
print(randomCV.fit(X_train,y_train))

c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\linear_model\_sag.py:349: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(


RandomizedSearchCV(cv=5, estimator=LogisticRegression(),
                   param_distributions={'C': [100, 10, 1.0, 0.1, 0.01],
                                        'penalty': ['l1', 'l2', 'elasticnet'],
                                        'solver': ['newton-cg', 'lbgfs',
                                                   'liblinear', 'sag',
                                                   'saga']},
                   scoring='accuracy')


c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning: 
30 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\arjun\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _

In [27]:
randomCV.best_score_

0.7242857142857143

In [28]:
randomCV.best_params_

{'solver': 'newton-cg', 'penalty': 'l2', 'C': 0.01}

In [29]:
y_pred=randomCV.predict(X_test)

In [30]:
score=accuracy_score(y_test,y_pred)
print(score)
cm=confusion_matrix(y_test,y_pred)
print(cm)
print(classification_report(y_test,y_pred))

0.7133333333333334
[[76 16 16]
 [21 64  7]
 [16 10 74]]
              precision    recall  f1-score   support

           0       0.67      0.70      0.69       108
           1       0.71      0.70      0.70        92
           2       0.76      0.74      0.75       100

    accuracy                           0.71       300
   macro avg       0.72      0.71      0.71       300
weighted avg       0.71      0.71      0.71       300

